version: "3.9"
services:
  redis:
    image: "redis"

  router:
    image: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/njs/jwt.js:/etc/nginx/njs/jwt.js
    ports:
      - "8080:8080"
    depends_on: ["authentication_guest", "advancewars_battlemap_create"]

  authentication_guest:
    image: "authentication_guest:local"
  advancewars_battlemap_create:
    image: "advancewars_battlemap_create:local"
    depends_on: ["redis"]